### ISSUE TITLE
KY Auto Rate

### ISSUE THREAD

**Issue by JordanPropp** [gobranch/rate_changes#1]
New rates filed to be effective on 4/25/22 can be found here.  https://drive.google.com/drive/folders/1DkZzU9wdYZ9rbRFPH68tH7VvyUTIHS13

Base rate only changes on RP.1

![image](https://user-images.githubusercontent.com/83597628/162970417-680d1d95-6eab-4c1e-a863-1dce0e54582e.png)

**Comment by matt-hewitt1** [comment]
These changes have been uploaded to ClarionDoor with effective date 4/25/2022. I will provide another update and close this ticket after the next production release (4/15/2022 at the latest).

**Comment by matt-hewitt1** [comment]
This update is now in production and will take effect on 4/25/2022. Closing this ticket.
