### ISSUE TITLE
OH Auto Rate Change

### ISSUE THREAD

**Issue by CoryCalway** [gobranch/rate_changes#11]
[OH Auto Update Pages.xlsx](https://github.com/gobranch/rate_changes/files/9507184/OH.Auto.Update.Pages.xlsx)

Updating OH base rates, Vehicle Symbol Factors, and Direct Discount eff 9/20 for NB and 11/4 for RN. 

Not yet approved but File and Use

Only changed pages are included for size.

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 9/20/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@jpappas23 please test and validate RN

**Comment by jpappas23** [comment]
Will do
