### ISSUE TITLE
MO Auto Rate change

### ISSUE THREAD

**Issue by Jacob945** [gobranch/rate_changes#12]
In this rate change we updated the base rate, vehicle symbol factors and direct discount. Tabs RP.1, VR.4 and DS.8
The new manual can be found here: https://drive.google.com/drive/folders/1tqFcKHpoT53x2HtNhnWFqLoXtqVYOr4i?usp=sharing
This change is planned to be effective 10/18/22 NB and 11/27/22 RN

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 10/18/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@rcraytonB please test and validate

**Comment by eperlman** [comment]
@rcraytonB please confirm ready to test and validate

**Comment by rcraytonB** [comment]
Tested and validated in dev environment.  Will test with a live policy when applicable.
