### ISSUE TITLE
Maryland HO Rate Base Rate Change

### ISSUE THREAD

**Issue by garrettdupuis** [gobranch/rate_changes#13]
With this we are updating the base rate.
Effective date 10/1/2022
[MD BIX HO Rate Change RP.1 Clean.pdf](https://github.com/gobranch/looker/files/9558684/MD.BIX.HO.Rate.Change.RP.1.Clean.pdf)

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 10/1/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@rcraytonB please test and validate
