### ISSUE TITLE
MI Home Rate - 12/15/22 NB 1/24/23 RB

### ISSUE THREAD

**Issue by JordanPropp** [gobranch/rate_changes#15]
## General ##
**State:** MI 
**New business effective date:** 12/15/22 
**Line of business:** Home
**Base Rate only**

## Attachment or link ##
[MI BIX HO RATE Manual 12.15.22 Home Rate.xlsx](https://github.com/gobranch/rate_changes/files/9633555/MI.BIX.HO.RATE.Manual.12.15.22.Home.Rate.xlsx)

## Filing law ##
Prior Approval, not yet approved.

**Comment by JordanPropp** [comment]
New rates attached above.

**Comment by matt-hewitt1** [comment]
These changes have been included in the most recent ClarionDoor production release. They will take effect for new business on 12/15/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@rcraytonB please confirm when ready to test and validate
