### ISSUE TITLE
NE Auto Rate Change

### ISSUE THREAD

**Issue by Dmclane1** [gobranch/rate_changes#16]
Update Base Rate and Direct Discount.
Effective Date for new Business - 9/30/2022
Effective Date for Renewal Business - 11/9/2022
[NE Auto Base Rate 202209 (Clean).pdf](https://github.com/gobranch/rate_changes/files/9569733/NE.Auto.Base.Rate.202209.Clean.pdf)
[NE Auto Direct Discount 202209 (Clean).pdf](https://github.com/gobranch/rate_changes/files/9569734/NE.Auto.Direct.Discount.202209.Clean.pdf)

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 9/30/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@pmcgeorge2 please test and validate
