### ISSUE TITLE
OKLAHOMA PPA Rate Change

### ISSUE THREAD

**Issue by Parsonsl5** [gobranch/rate_changes#18]
OK PPA Rate Change effective 9/28/2022 for New and 11/07/2022 for Renewals.

Elements changing:
   Rates:  Base Rates (RP.1), Symbol Table (VR.4) and Direct Discount (DS.8)
   Rules:  Rule 31-Affinity Partner Change

Files due to size are in OK 202209 in Launch under OK.

**Comment by matt-hewitt1** [comment]
These changes have been made in ClarionDoor. I will update and close this ticket once a new production release has been deployed.

**Comment by Parsonsl5** [comment]
Thanks Matt!
--
Larry Parsons
Insurance Product Manager
C: 614.302.1276
Getting back to getting each other's back.

**Comment by matt-hewitt1** [comment]
These changes have been included in the most recent ClarionDoor production release. They will take effect for new business on 9/28/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@jpappas23 please test and validate

**Comment by jpappas23** [comment]
Yup, will do.
