### ISSUE TITLE
Rate Change - PA  Home- NB 10.1.22 RB 11.15.22

### ISSUE THREAD

**Issue by madina-salemi** [gobranch/rate_changes#19]
## General ##
**PA:** 
**10.1.22:** 
**Home:** 
**Description of changes:** *RP.1 base rate change +5%*

## Attachment or link ##
[https://docs.google.com/spreadsheets/d/1YBaph_uYpTBDA5xR71tDBhCDvAPuXws1/edit?usp=sharing&ouid=117303335779700020627&rtpof=true&sd=true](url)

## Filing law ##
*prior approval state - APPROVED 9.20.22

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 10/1/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@pmcgeorge2 please add to calendar/task list to test and validate

**Comment by pmcgeorge2** [comment]
RN tested and validated.
