### ISSUE TITLE
Rate Change - KS Home - NB 10/1 RN 11/15

### ISSUE THREAD

**Issue by Jacob945** [gobranch/rate_changes#20]
## General ##
KS 
NB 10/1/22
Home
Updated tabs: ZR.1, ZD.1, RP.1, RP.13
We updated the affinity groups and base rates. I also added zip 66742 to the ZR and ZD tables.

## Attachment or link ##
This link has all docs involved (if you need to see tracked changes) https://drive.google.com/drive/folders/1VIxPHSU4qGYDfnX6laAc4UYEC5FLGRJG?usp=sharing

This is the link to the clean updated manual:
https://docs.google.com/spreadsheets/d/1f-KKuc4j4nGWbapHoIyt8RdzPE6ftkPf/edit?usp=sharing&ouid=101050851715750913272&rtpof=true&sd=true

## Filing law ##
use and file- this may get pushback but still go with 10/1/22

**Comment by eperlman** [comment]
@jpappas23 please add to your calendar to test and validate

**Comment by jpappas23** [comment]
@eperlman will do, thanks!

**Comment by Jacob945** [comment]
This got approved today, this will be effective 10/1/22

**Comment by jpappas23** [comment]
Thanks @Jacob945

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 10/1/2022 with no further action.

Closing this ticket.
