### ISSUE TITLE
Rate Change - <TX Auto> - <10/08/2022>

### ISSUE THREAD

**Issue by Parsonsl5** [gobranch/rate_changes#23]
## General ##
**State:TX
**New business effective date:10/08/2022 
**Line of business:** *Auto*
**Description of changes:** *RP.1, VR.4, DS.8*

## Attachment or link ##
*the full rate manual may be too large to attach; if so, a file with only the updated tabs can be attached*
*for factor tables, Excel format is preferred over PDF*
*if a folder link is provided, please ensure that there is only one version of rules/rates in the folder*

## Filing law ##
*File and Use filed early* 
*Change under scrutiny due to size*

## Additional ##
*No*
[Github Pages BIX TX PPA 10 08 2022.xlsx](https://github.com/gobranch/rate_changes/files/9629618/Github.Pages.BIX.TX.PPA.10.08.2022.xlsx)
These pages will be in the TX Launch Folder

**Comment by matt-hewitt1** [comment]
Hi @Parsonsl5! There seem to be issues with a few of the rows in the new version of the TX auto vehicle symbol factor table. For example, the rows shown in the screenshot below; also, there appear to be duplicate rows (at least for make/model/symbol C2, D2, E2, F2, and G2).

Would you mind taking a look and posting a revised version, if necessary? I'd like to include these updates in a ClarionDoor release scheduled for today.

![image](https://user-images.githubusercontent.com/54377302/192005153-d2bffd20-9fc0-4e69-8de0-4332ef5f6e3c.png)

**Comment by eperlman** [comment]
@jpappas23 please test and validate when confirmed ready for testing

**Comment by jpappas23** [comment]
Will do @eperlman

**Comment by matt-hewitt1** [comment]
These changes have been included in the most recent ClarionDoor production release. They will take effect for new business on 10/8/2022 with no further action.

Closing this ticket now.

**Comment by rcraytonB** [comment]
Tested and Validated
