### ISSUE TITLE
Rate Change -OH Home 10/15/22

### ISSUE THREAD

**Issue by CoryCalway** [gobranch/rate_changes#24]
OH Homeowners Rate Change
OH
10/15/22 NB 11/29/22 Renewal
Homeowners
Base Rate Change - Rate manual RP.1, no other changes
[Ohio BIX HO RATE manual 202210.xlsx](https://github.com/gobranch/rate_changes/files/9676205/Ohio.BIX.HO.RATE.manual.202210.xlsx)
File and Use

**Comment by matt-hewitt1** [comment]
These changes have been included in the most recent ClarionDoor production release. They will take effect for new business on 10/15/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.
