### ISSUE TITLE
Rate Change - <MO Home> - <11/1/22>

### ISSUE THREAD

**Issue by Jacob945** [gobranch/rate_changes#26]
## General ##
**MO** 
**11/1/22 NB 12/16/22 RB** 
**Home**
**Description of changes:** *RP.1*

## Attachment or link ##
*the full rate manual may be too large to attach; if so, a file with only the updated tabs can be attached*
*for factor tables, Excel format is preferred over PDF*
*if a folder link is provided, please ensure that there is only one version of rules/rates in the folder*
https://drive.google.com/drive/folders/1WAmV6VczyLfL537aHOv8xmYbjKEKyoRr?usp=sharing

## Filing law ##
*use and file*
*I do not expect pushback on this filing*

**Comment by matt-hewitt1** [comment]
These changes have been included in the most recent ClarionDoor production release. They will take effect for new business on 11/1/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by Jacob945** [comment]
We are good to go on this ticket, this is a file and use filing.

**Comment by rcraytonB** [comment]
Tested and validated in the dev environment. Will test and validate on policy in live environment
