### ISSUE TITLE
Rate Change - IN - <Effective 10/18/22 >

### ISSUE THREAD

**Issue by JenAdd** [gobranch/rate_changes#27]
Rate Change
Indiana
[Rate Change.xlsx](https://github.com/gobranch/rate_changes/files/9747947/Rate.Change.xlsx)

**NB Effective 10/18/22:** 
Auto 
Changes to RP1, DS8, VR.4

**Comment by matt-hewitt1** [comment]
These changes have been included in the most recent ClarionDoor production release. They will take effect for new business on 10/18/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@pmcgeorge2 please confirm ready to test and validate

**Comment by eperlman** [comment]
@JenAdd please confirm RN effective date

**Comment by JenAdd** [comment]
The Renewal effective date is 11/27/22
