### ISSUE TITLE
Private Fire Company Credit - AZ - NB 10/31/22

### ISSUE THREAD

**Issue by Jaclyn-deMedicciBruneau** [gobranch/rate_changes#28]
Private Fire Company Credit factor update
Arizona
NB 10/31/22
Condo
The Private Fire Company Credit factor has been updated to the correct factor of 0.985 and removed from the Affinity Groupings to standalone. RP.9 in the Rate Manual

This was approved very quickly upon filing- becomes effective 10/31/22.  Only eligible in two specific zip codes so impact minimal.

[AZ BIX Condo RATE Manual RP.9 CLEAN.pdf](https://github.com/gobranch/rate_changes/files/9814092/AZ.BIX.Condo.RATE.Manual.RP.9.CLEAN.pdf)
[AZ BIX Condo RATE Manual RP.9 REDLINEpdf.pdf](https://github.com/gobranch/rate_changes/files/9814093/AZ.BIX.Condo.RATE.Manual.RP.9.REDLINEpdf.pdf)

**Comment by eperlman** [comment]
@jpappas23 please test and validate when effective
@Jaclyn-deMedicciBruneau is this update for NB & RN if so please advise regarding effect date

**Comment by Jaclyn-deMedicciBruneau** [comment]
@eperlman NB/RN 10/31/22

**Comment by jpappas23** [comment]
@eperlman Will do, thanks

**Comment by matt-hewitt1** [comment]
Hi @Jaclyn-deMedicciBruneau! This is for AZ condo, which will not be live by 10/31 - so we just need to have this change incorporated at launch, right?

**Comment by Jaclyn-deMedicciBruneau** [comment]
@matt-hewitt1 You are correct- filing is 10/31 but not a high priority as long as incorporated by launch date.

**Comment by matt-hewitt1** [comment]
Thanks, @Jaclyn-deMedicciBruneau!

@jicho2 and @kristenreed4 - tagging you to make sure this is incorporated prior to AZ condo launch. You can close this ticket once it has been addressed.

**Comment by jicho2** [comment]
This had been incorporated into the rater and ClarionDoor tables. Thank you.

**Comment by Jaclyn-deMedicciBruneau** [comment]
@jicho2 thank you!
