### ISSUE TITLE
Rate Change - Wyoming Auto - 10/28/2022

### ISSUE THREAD

**Issue by j-koleski** [gobranch/rate_changes#29]
## General ##
**State:** Wyoming
**New business effective date:** 10/28/2022 
**Line of business:**Auto
**Description of changes:** Direct factor changed from 0.1 to 0.0

## Attachment or link ##
[WY PPA Rate Page DS.8.xlsx](https://github.com/gobranch/rate_changes/files/9839083/WY.PPA.Rate.Page.DS.8.xlsx)

## Filing law ##
Wyoming is a no-file state so implementation on 10/28/2022 needs no further approval.

## Additional ##
Nope!

**Comment by eperlman** [comment]
@rcraytonB please test and validate when implemented

**Comment by matt-hewitt1** [comment]
This change has now been made in ClarionDoor. I will comment and close this ticket after the next CD production release.

**Comment by matt-hewitt1** [comment]
These changes are now in production and will take effect on 10/28/22 with no further action.

Closing this ticket. Please reopen if there are any changes to this filing or effective date.

**Comment by rcraytonB** [comment]
tested in the dev environment and validated. Will retest with applicable live policy.
