### ISSUE TITLE
NH Home Rate Change

### ISSUE THREAD

**Issue by Jacob945** [gobranch/rate_changes#3]
We have filed a rate change to be effective 8/19/2022 in NH. The updated base rates can be found here:
https://drive.google.com/drive/folders/1S8rxYCNH7sJ96WwhSOxgmck3ynWVf21H?usp=sharing

**Comment by matt-hewitt1** [comment]
This change has been pushed to production with an effective date of 8/19/22, so with no further action, the new base rates will take effect on that date. Closing this ticket - please re-open if there is any change to this filing.
