### ISSUE TITLE
Rate Change - <state> - <new business effective date>

### ISSUE THREAD

**Issue by Dmclane1** [gobranch/rate_changes#30]
## General ##
**Nebraska:** 
**New business effective date: 11/21/2022: Renewal: 1/05/2023** 
**Line of business:** *home.*
**Description of changes:** *RP.1*

## Attachment or link ##
*the full rate manual may be too large to attach; if so, a file with only the updated tabs can be attached*
*for factor tables, Excel format is preferred over PDF*
[NE Home Rate Manual 202210 (Clean).pdf](https://github.com/gobranch/rate_changes/files/9840784/NE.Home.Rate.Manual.202210.Clean.pdf)

*if a folder link is provided, please ensure that there is only one version of rules/rates in the folder*

## Filing law ##
*file and use*
*do we anticipate pushback? is there any other reason we might want to wait to load these changes?*
More than likely no objections 
## Additional ##
*is there anything else you'd like us to know?*

**Comment by matt-hewitt1** [comment]
This change has now been made in ClarionDoor. I will comment and close this ticket after the next CD production release.

**Comment by eperlman** [comment]
@pmcgeorge2 please confirm when ready to test and validate

**Comment by matt-hewitt1** [comment]
These changes are now in production and will take effect on 11/21/22 with no further action.

Closing this ticket. Please reopen if there are any changes to this filing or effective date.
