### ISSUE TITLE
MI Auto - 9/22 NB, 11/1 RN

### ISSUE THREAD

**Issue by JordanPropp** [gobranch/rate_changes#4]
Updating MI base rates, eff 9/22 for NB and 11/1 for RN.  Not yet approved

https://drive.google.com/drive/folders/1_TiYORTFIPkNwIQL4MmMrqcrzW-sMe9s

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 9/22/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.
