### ISSUE TITLE
TX HO Rate Change

### ISSUE THREAD

**Issue by Parsonsl5** [gobranch/rate_changes#5]
Attached are revised TX HO rates: pages changing are RP-1 and all ZR pages.  The filing is effective 8-26-2022 for new and 10-10-2022 for renewals.  The impact of the change is 25%, so significant high priority.
[TX BIX HO Rating Manual Clean 202208.xlsx](https://github.com/gobranch/rate_changes/files/9236954/TX.BIX.HO.Rating.Manual.Clean.202208.xlsx)

**Comment by matt-hewitt1** [comment]
These updates have been incorporated into the rater with effective date 8/26/22, and will be included in the next ClarionDoor production release (this will occur prior to 8/26/22). I will update and close this ticket once the new release is live.

**Comment by matt-hewitt1** [comment]
These updates are now in production and will take effect on 8/26/22 with no further action. Closing this ticket - please reopen if this filing change is delayed/modified.
