### ISSUE TITLE
AZ HO Rate Change

### ISSUE THREAD

**Issue by Jaclyn-deMedicciBruneau** [gobranch/rate_changes#6]
Attached please find the updated AZ Ho rate manual; only changes are to RP.1.  Effective 9/15 NB 10/30 RN with a 10.0% increase.  Thank you
[AZ HO RATE manual - 202208.xlsx](https://github.com/gobranch/rate_changes/files/9311420/AZ.HO.RATE.manual.-.202208.xlsx)

**Comment by matt-hewitt1** [comment]
These updates are now in production and will take effect on 9/15/22 with no further action. Closing this ticket - please reopen if this filing change is delayed/modified.
