### ISSUE TITLE
OR HO Rate Change

### ISSUE THREAD

**Issue by Jaclyn-deMedicciBruneau** [gobranch/rate_changes#7]
Attached please find the updated OR HO Rate Manual.  Changes are to RP.1.  Effective 09/01 NB 10/17 RN with a 20.0% increase.  Thank you. 
[OR Home Rate Manual 202208.xlsx](https://github.com/gobranch/rate_changes/files/9311449/OR.Home.Rate.Manual.202208.xlsx)

**Comment by matt-hewitt1** [comment]
These updates are now in production and will take effect on 9/1/22 with no further action. Closing this ticket - please reopen if this filing change is delayed/modified.

**Comment by eperlman** [comment]
@pmcgeorge2 please add to calendar/tasks to test and validate RN

**Comment by eperlman** [comment]
@pmcgeorge2 please confirm if RN is ready to test and validate
