### ISSUE TITLE
PA Auto Rate Increase

### ISSUE THREAD

**Issue by madina-salemi** [gobranch/rate_changes#8]
Attached please find the updated PA PPA Rate Manual. Changes are to RP.1. Effective 8/15  with a 9.0% increase. Thank you.  [PA PPA Rate Manual 08.2022](https://drive.google.com/file/d/19ap4s2YJUpjmJGOSSsKg7SGMawaqXFap/view?usp=sharing)

**Comment by matt-hewitt1** [comment]
These changes have been made and included in the CD production release today. The new base rates will go into effect on 8/15/22. Closing this ticket.
