### ISSUE TITLE
ID Auto - 8/1 NB, 9/10 RN

### ISSUE THREAD

**Issue by ScottBlum2** [gobranch/rate_changes#9]
Updating ID RP.1 RP.4 and FX.1 eff 8/1 for NB and 9/10 for RN. Has gotten State Approval. Change implemented around AUG 1 in CD. Making this ticket for documentation purposes only.  https://drive.google.com/drive/folders/1lQzmhunDEwqixo0byNWD1Jjc_uRuNTYP

**Comment by matt-hewitt1** [comment]
Update completed and live as of 8/1/22. Closing ticket.
